export const reports = [
    {
        jobId: "1",
        unit: "งานผู้ป่วยนอก",
        issue: "คอมเปิดไม่ติด",
        symptom: "เปิดไม่ติด",
        reportDate: "02/12/2024 10:18:49",
        status: "รอดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "2",
        unit: "งานไอที",
        issue: "เครื่องปริ้นเสีย",
        symptom: "กระดาษติด",
        reportDate: "03/12/2024 11:30:10",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "3",
        unit: "งานผู้ป่วยใน",
        issue: "ไฟฟ้าดับ",
        symptom: "ไม่สามารถเปิดอุปกรณ์ได้",
        reportDate: "04/12/2024 08:50:25",
        status: "เสร็จสิ้น",
        completionDate: "04/12/2024 12:00:00",
    },
    {
        jobId: "4",
        unit: "งานผู้ป่วยนอก",
        issue: "คอมเปิดไม่ติด",
        symptom: "เปิดไม่ติด",
        reportDate: "05/12/2024 09:45:13",
        status: "รอดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "5",
        unit: "งานเภสัชกรรม",
        issue: "ลิฟต์ค้าง",
        symptom: "ไม่ตอบสนอง",
        reportDate: "06/12/2024 14:20:55",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "6",
        unit: "งานซ่อมบำรุง",
        issue: "หลอดไฟเสีย",
        symptom: "แสงไม่ติด",
        reportDate: "07/12/2024 10:18:33",
        status: "เสร็จสิ้น",
        completionDate: "07/12/2024 12:45:00",
    },
    {
        jobId: "7",
        unit: "งานผู้ป่วยใน",
        issue: "เตียงไฟฟ้าขัดข้อง",
        symptom: "ปรับระดับไม่ได้",
        reportDate: "08/12/2024 09:10:50",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "8",
        unit: "งานไอที",
        issue: "อินเทอร์เน็ตล่ม",
        symptom: "เชื่อมต่อไม่ได้",
        reportDate: "09/12/2024 11:15:40",
        status: "รอดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "9",
        unit: "งานเวชระเบียน",
        issue: "เครื่องปริ้นไม่ทำงาน",
        symptom: "ไม่มีการพิมพ์ออกมา",
        reportDate: "10/12/2024 08:50:00",
        status: "เสร็จสิ้น",
        completionDate: "10/12/2024 13:20:00",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    },
    {
        jobId: "10",
        unit: "งานซ่อมบำรุง",
        issue: "ประตูเลื่อนขัดข้อง",
        symptom: "เปิด-ปิดไม่ได้",
        reportDate: "11/12/2024 10:00:15",
        status: "กำลังดำเนินการ",
        completionDate: "",
    }
]