import type { Metadata } from "next";
import "@/styles/globals.css"
import { Noto_Sans_Thai } from 'next/font/google';
import Layout from "@/containers/(guest)/layout";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
    title: "เว็บแจ้งซ่อม",
    description: "Generated by create next app",
};

const notoSansThai = Noto_Sans_Thai({
    subsets: ['thai']
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="th">
            <body className={notoSansThai.className + " min-h-screen"}>
                <ToastContainer />
                <Layout>
                    {children}
                </Layout>
            </body>
        </html>
    );
}
